### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by KoenPaas** [OnTheDEX/xrpledger-token-data-api#1]
What would be missing from this API is a few different endpoints with different aggregation results:

- market price for a specific token pair like XRP to GateHub USD
expected to at least return:
```
{
    last_traded_price: 0.345678,
    trend: 'up', // or down. this is compared to the second last traded price
}
```

Also an endpoint for market data for a specific token pair for the rolling 24h  (If i'm not missing any value that could be in here) etc:
```
{
    high: 0.600000,
    24h_last_traded_price: 0.450000,
    low: 0.400000,
    volume_base: 1000,
    volume_quote: 1200
}
```

An addition to this endpoint for example: `'https://api.onthedex.live/public/v1/daily/pairs?token=XRP'`
```
{
    change: 0.023 // a percentage that calculates the change between the 24h_last_traded_price with the current last_trasde_price
    24h_last_traded_price: 0.400000 // or is this the mid price?
    current_market_price: 0.4100000 // last traded price
}
```

**Comment by OnTheDEX** [comment]
Thank you, Koen!  The API has been updated to offer the above: please check the properties available in the `/daily/pairs` endpoint for `ago24`, `last`, `pc24` and `trend` which cover the data points you request above; this endpoint can now also specify a `quote` currency to return just one pair if desired.
