### ISSUE TITLE
2nd call marker is missing

### ISSUE THREAD

**Issue by zgrguric** [OnTheDEX/xrpledger-token-data-api#2]
Consider initial request:
`https://api.onthedex.live/public/v1/ohlc?base=534F4C4F00000000000000000000000000000000.rsoLo2S1kiGeCcn6hCUXVrCpGMWLrRrLZz&quote=XRP&bars=100&tf=ISO&cf=yes&interval=15`

Marker is returned.

Now next request (with marker from previous):
`https://api.onthedex.live/public/v1/ohlc?base=534F4C4F00000000000000000000000000000000.rsoLo2S1kiGeCcn6hCUXVrCpGMWLrRrLZz&quote=XRP&bars=100&tf=ISO&cf=yes&interval=15&marker=1682335800%7C100%7C100%7C15`

In response of 2nd request, marker is missing, one is unable to load history more than one time.

**Comment by OnTheDEX** [comment]
Fixed.  Thanks for your report.
